/**
 * Every word the app says, in one place, so `make copy-check` can read them
 * and so the circle's languages (ADR-0006 #12) have somewhere to go. The
 * calm rules from DESIGN.md: plain words, no exclamation, the official
 * numbers first.
 */
export const t = {
  appName: 'Sentinel',
  tagline: 'Your circle, told. Nobody else.',
  home: 'Tonight',
  officialFirst: 'If you are in danger now, call',
  notASubstitute: 'Sentinel is not a substitute for the emergency services.',
  panic: 'Alert my circle',
  panicHint: 'Sends your position to the people you chose, now. Nothing to strangers.',
  panicSilent: 'Held silently',
  journeyStart: 'Start a journey',
  journeyHint: 'Say where and when. If you do not confirm arriving, your circle is told with your last position.',
  circle: 'My circle',
  circleEmpty: 'Nobody yet. Add someone who would want to know.',
  circleHint: 'They accept first. Either of you can end it at any time, without saying why.',
  whoCanSeeMe: 'Who can see where I am, right now',
  onlyDuringAlert: 'only during an alert',
  thisJourneyUntil: 'this journey, until',
  alertInProgress: 'alert in progress',
  alertSentTo: 'Your circle has been told.',
  alertNobody: 'There is nobody in your circle to tell. Call the number above.',
  delivering: 'Reaching your circle.',
  notDelivered: 'Your circle could not be reached. Call the number above.',
  acknowledgedBy: 'acknowledged',
  notYetAcknowledged: 'not yet',
  cancelAlert: 'I am safe — end the alert',
  cancelHow: 'Hold with two fingers for two seconds, then your PIN.',
  drill: 'This is a drill',
  arrived: 'I have arrived',
  areYouHome: 'Are you there?',
  settings: 'Settings',
  plainSurfaces: 'Plain surfaces',
  lessMotion: 'Less motion',
  largeControls: 'Large controls',
  invited: 'invited, not yet accepted',
  invite: 'Invite',
  remove: 'Remove',
  phoneNumber: 'Phone number',
  back: 'Back',
  where: 'Where to',
  minutesFromNow: 'Minutes from now',
  whoToTell: 'Who to tell if you do not confirm',
  telling: 'Telling',
  notTelling: 'Not telling',
  whatHappens: 'What happens',
  planLine: (ask: number, escalate: number) =>
    `In ${ask} minutes the phone asks if you have arrived. If you do not answer, after ${escalate} minutes the people above are told where you were.`,
  serverEscalates: 'That happens even if the phone dies or has no signal.',
  batteryShort: 'The battery may not last this journey. The people above are still told.',
  journeyGo: 'Start',
  journeyUnderway: (where: string, minutes: number) => `On the way to ${where}. Expected in ${minutes} minutes.`,
  journeyEscalated: 'You did not confirm. Your circle has been told where you were.',
  yourNumber: 'Your number',
  yourName: 'Your name, as your circle knows you',
  settingsHint: 'Your number becomes a code before it leaves this phone. Your name is only ever sent to your circle.',
  save: 'Save',
  notSealed: 'could not be reached: their phone has not joined Sentinel yet',
  noPosition: 'Sent without a position. This phone had no fix.',
  enterPin: 'Your PIN',
  pin: 'PIN',
  duressPin: 'Duress PIN',
  pinsHint: 'Two PINs, four to six digits, different from each other. The second one opens a screen that looks idle and tells your circle you were made to.',
  savePins: 'Save PINs',
  holdToCancel: 'Hold here with two fingers',
  panicHold: 'Hold the alert button to send silently: nothing on this screen changes.',
  reveal: 'Show',
  wrongPin: 'That is not your PIN.',
  knows: 'What Sentinel knows about you',
  knowsNumber: (code: string) => `Your number, as a code: ${code}…`,
  knowsNoNumber: 'No number yet.',
  knowsName: (name: string) => `Your name, sent only to your circle: ${name}`,
  knowsCircle: (n: number) => `${n} in your circle, each as a code`,
  knowsAlerts: (n: number) => `${n} alert records kept on this phone, and nowhere else`,
  knowsKeys: 'Two keys made on this phone, kept in its secure store. The server holds the public halves.',
  knowsKeysLaunch: 'Two keys made for this launch only; this phone has no secure store for them. The server holds the public halves.',
  knowsNothingElse: 'Nothing else. No location is kept; no location is ever readable by the server.',
  shareRecord: 'Share the last alert record',
  shareRecordHint: 'Signed by this phone. Anyone can check it with scripts/verify-record.py.',
  welcome: 'Before anything else',
  rule1: 'If you are in danger now, call the number. Sentinel is not a substitute for it.',
  rule2: 'The alert button tells the people you chose where you are. Nobody else, ever.',
  rule3: 'Hold the button to send silently. To end an alert, hold with two fingers for two seconds, then your PIN.',
  rule4: 'Nothing here is ever about a person. Sentinel refuses names, descriptions and plates, on purpose.',
  begin: 'Add my number',
  nearby: 'Near you',
  nearbyHint: 'Events at places, from people within reach of them. Nothing here is about a person.',
  nearbyEmpty: 'Nothing within reach of where you are.',
  nearbyNoPosition: 'Sentinel needs to know where you are to show what is near you. This phone has no fix.',
  nearbyUnreachable: 'Sentinel could not be reached. Nothing here is current.',
  reportSomething: 'Report something',
  reportHint: 'Pick what happened and where you are. You may add a sentence about the event; it is checked here before it goes anywhere.',
  reportNoPosition: 'A report is an event at a place, and this phone has no fix. It cannot be sent.',
  whatHappened: 'What happened',
  describeEvent: 'About the event, if you like',
  send: 'Send',
  blockedTitle: 'That cannot be sent',
  blockedHint: 'Sentinel is never about a person. Describe the event instead: what happened, where, and when.',
  reasonName: 'It names someone.',
  reasonDescription: 'It describes what someone looks like.',
  reasonClothing: 'It describes what someone is wearing.',
  reasonIdentifier: 'It names an ethnic or religious group.',
  reasonPlate: 'It carries a vehicle plate.',
  reasonPhone: 'It carries a phone number.',
  reasonScreener: 'The check is not available right now; the category and the place can still be sent.',
  reasonTooMany: 'You have reported recently. Try again later.',
  reasonNoAccount: 'Add your number in Settings first.',
  refusedUnreachable: 'Sentinel could not be reached. Nothing was sent.',
  sawItToo: 'I saw this too',
  disputeIt: 'That is not right',
  disputeWhy: 'What is not right',
  withdrawMine: 'Take back my report',
  corrected: 'A report you were shown has been taken back by the person who made it.',
  stageReported: 'one report',
  stageCorroborated: 'seen by others',
  stageConfirmed: 'confirmed',
  stageVerified: 'verified',
  minutesAgo: (m: number) => (m < 1 ? 'just now' : m < 60 ? `${m} min ago` : `${Math.floor(m / 60)} h ago`),
  aboutMetres: (m: number) => (m < 100 ? 'very near' : `about ${Math.round(m / 100) * 100} m away`),
  category: {
    robbery: 'Robbery',
    burglary: 'Burglary',
    road_blocked: 'Road blocked',
    accident: 'Accident',
    fire: 'Fire',
    flooding: 'Flooding',
    gunfire_heard: 'Gunfire heard',
    unrest_or_protest: 'Unrest or protest',
    building_collapse: 'Building collapse',
    power_line_down: 'Power line down',
    missing_person_appeal: 'Missing person appeal',
  } as Record<string, string>,
  disputeReason: {
    didnt_happen: 'It did not happen',
    wrong_place: 'Wrong place',
    already_over: 'It is already over',
    duplicate: 'Already reported',
  } as Record<string, string>,
} as const;
